### ISSUE TITLE
Error while getting console.

### ISSUE THREAD

**Issue by duongtruong12** [liferay/liferay-mobile-sdk#69]
i got this Message while run command on git bash, i even run all command include './gradlew createModule --no-daemon'

Quang Truong@QuangTruong-PC MINGW64 /e/Android/AnroidProject/liferay-mobile-sdk (builder-7.0.0)
$ ./gradlew createModule -P=all
:createModule
Error while getting console.
:builder:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning

:builder:processResources
:builder:classes
:builder:jar
:generateAug 27, 2018 1:56:11 PM com.liferay.mobile.sdk.SDKBuilder main
SEVERE: org.json.JSONException: JSONObject["basePath"] not found.
java.io.IOException: org.json.JSONException: JSONObject["basePath"] not found.
        at com.liferay.mobile.sdk.http.DiscoveryResponseHandler.handleResponse(DiscoveryResponseHandler.java:38)
        at com.liferay.mobile.sdk.http.DiscoveryResponseHandler.handleResponse(DiscoveryResponseHandler.java:28)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1142)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1076)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1050)
        at com.liferay.mobile.sdk.SDKBuilder.discover(SDKBuilder.java:126)
        at com.liferay.mobile.sdk.SDKBuilder.build(SDKBuilder.java:75)
        at com.liferay.mobile.sdk.SDKBuilder.main(SDKBuilder.java:53)
Caused by: org.json.JSONException: JSONObject["basePath"] not found.
        at org.json.JSONObject.get(JSONObject.java:473)
        at org.json.JSONObject.getString(JSONObject.java:654)
        at com.liferay.mobile.sdk.http.Discovery.<init>(Discovery.java:33)
        at com.liferay.mobile.sdk.http.DiscoveryResponseHandler.handleResponse(DiscoveryResponseHandler.java:35)
        ... 7 more

BUILD SUCCESSFUL

Total time: 37.06 secs

**Comment by nhpatt** [comment]
Closing, please reopen if necessary :)
